### ISSUE TITLE
pip requirements.txt lists feaTools revision that doesn't exist

### ISSUE THREAD

**Issue by sladen** [daltonmaag/scope-one#16]
Running:

`$ pip install -r requirements.txt`

will fail because the preferred revision listed for `daltonmaag/feaTools` does not exist in the present repo:
```
$ tail -n2 requirements.txt 
# feaTools (from py23 branch on DaMa fork)
-e git+https://github.com/daltonmaag/feaTools.git@98aae9d5d8f6748aaf9e80198b43bae7bed9c78b#egg=feaTools
```

**Comment by anthrotype** [comment]
Hi Paul,
thanks for looking at the code.

Did you have the same issue as the one reported by @felipesanches in https://github.com/daltonmaag/scope-one/pull/13?

I realised that some time ago, I had rebased the daltonmaag/py23 branch of feaTools on the upstream's master, I guess that's the reason why pip was failing (though it still seems to work on my side.. might be some caching thing).

Anyway, I updated the commit hash (https://github.com/daltonmaag/scope-one/commit/9249352f46ffc21292ddb503fe497c950331b2b5) so it should work now.
 
As I said to Felipe, feaTools is not even needed for Scope One: it's simply imported by ufo2ft so we had to include it in the requirements.txt to avoid ImportError.

Btw, a few weeks ago, I sent a pull request with the py23 fixes to typesupply/feaTools.
https://github.com/typesupply/feaTools/pull/9
