### ISSUE TITLE
pip requirements for fonttools for unichr = unichr on Python 2.x wide

### ISSUE THREAD

**Issue by sladen** [daltonmaag/scope-one#17]
In `requirements.txt`, at least commit 2eda is required for `py23.unichr` to function under Python 2.x:

https://github.com/daltonmaag/fonttools/commit/2eda1785f654125342f6b517e707b24bff92d18c

**Comment by davelab6** [comment]
Isn't this all meant to be python3?

**Comment by moyogo** [comment]
Yes, Python 3.3+ is in the list of requirements.
Some of the requirements are only python3 at the moment: defcon, ufo2fdk, robofab.
